name = "frontis-gateway"
main = "index.ts"
compatibility_date = "2026-03-13"
compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "Text"
globs = ["**/*.graphql", "**/*.html"]
fallthrough = false

[dev]
inspector_port = 9232

[observability]
enabled = true
head_sampling_rate = 1

[[services]]
binding = "ECHO"
service = "frontis-echo"

[[services]]
binding = "SPECIALTIES"
service = "frontis-specialties"

[[services]]
binding = "CLUBS"
service = "frontis-clubs"

[[services]]
binding = "COMPETITIONS"
service = "frontis-competitions"

[[services]]
binding = "RESULTS"
service = "frontis-results"

[vars]
ENVIRONMENT = "dev"
GRAPHQL_MAX_DEPTH = "7"
GRAPHQL_MAX_TOKENS = "1000"
GRAPHQL_MAX_DIRECTIVES = "10"

[[kv_namespaces]]
binding = "SUPERGRAPH_CACHE"
id = "9b61ecdddbf84363a2b9d7f886aec23a"

[env.production.vars]
ENVIRONMENT = "production"
GRAPHQL_MAX_DEPTH = "7"
GRAPHQL_MAX_TOKENS = "1000"
GRAPHQL_MAX_DIRECTIVES = "10"

[[env.production.kv_namespaces]]
binding = "SUPERGRAPH_CACHE"
id = "9b61ecdddbf84363a2b9d7f886aec23a"
