# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

name = "frontis-clubs"
main = "index.ts"
compatibility_date = "2026-03-13"
compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "Text"
globs = ["**/*.graphql"]
fallthrough = false

[dev]
inspector_port = 9230
persist_to = "../../.wrangler/state"

[[d1_databases]]
binding = "DB_LEAGUE_LCAPB"
database_name = "pilotariak_lcapb"
database_id = "f2344757-9f73-4e16-bca9-554331062864"

[[d1_databases]]
binding = "DB_LEAGUE_LIDFPB"
database_name = "pilotariak_lidfpb"
database_id = "7672f60e-bd73-423e-ba92-d073c69d9c07"

[observability]
enabled = true
head_sampling_rate = 1
