name = "frontis-competitions"
main = "index.ts"
compatibility_date = "2026-03-13"
compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "Text"
globs = ["**/*.graphql"]
fallthrough = false

[dev]
inspector_port = 9231

[observability]
enabled = true
head_sampling_rate = 1
