# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
name: Deploy / Worker
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy-subgraphs:
    name: Deploy ${{ matrix.subgraph }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: production
    strategy:
      matrix:
        subgraph:
          - echo
          - clubs
          - competitions
          - results
          - specialties
      fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Build & Deploy ${{ matrix.subgraph }}
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "subgraphs/${{ matrix.subgraph }}"

  deploy-gateway:
    name: Deploy Gateway
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: production
    needs: deploy-subgraphs
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Build & Deploy Gateway
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "gateway"
